
# --- Main Colors ---
background            #101418
foreground            #e0e2e8
cursor                #e0e2e8
cursor_text_color     #101418

selection_background  #3a4857
selection_foreground  #d5e4f7

url_color             #d3bfe6

# --- ANSI Colors ---
color0                #101418
color1                #ffb4ab
color2                #d3bfe6
color3                #b9c8da
color4                #9bcbfb
color5                #d3bfe6
color6                #b9c8da
color7                #e0e2e8

color8                #42474e
color9                #93000a
color10               #504061
color11               #3a4857
color12               #0e4a73
color13               #3a4857
color14               #504061
color15               #c2c7cf

# --- Starship Prompt Bubbles ---
color255              #0e4a73
color254              #9bcbfb
color253              #3a4857
color252              #b9c8da
color251              #504061
color250              #d3bfe6
color249              #93000a
color248              #ffb4ab

color232              #cee5ff
color233              #003353
color234              #d5e4f7
color235              #233240
color236              #efdbff
color237              #382a49
color238              #ffdad6
color239              #690005
color240              #cee5ff

# Matched with unthemed light/dark
color243              #9bcbfb
color244              #ffb4ab
color245              #42474e

# --- UI Elements ---
active_tab_foreground   #003353
active_tab_background   #9bcbfb
inactive_tab_foreground #cee5ff
inactive_tab_background #0e4a73

active_border_color     #9bcbfb
inactive_border_color   #8c9198

# --- Marks ---
mark1_foreground        #001d33
mark1_background        #cee5ff
mark2_foreground        #0e1d2a
mark2_background        #d5e4f7
mark3_foreground        #231533
mark3_background        #efdbff