
# --- Main Colors ---
background            #101417
foreground            #e0e3e8
cursor                #e0e3e8
cursor_text_color     #101417

selection_background  #384956
selection_foreground  #d3e5f6

url_color             #d0c0e8

# --- ANSI Colors ---
color0                #101417
color1                #ffb4ab
color2                #d0c0e8
color3                #b7c9d9
color4                #96ccf8
color5                #d0c0e8
color6                #b7c9d9
color7                #e0e3e8

color8                #41474d
color9                #93000a
color10               #4d4162
color11               #384956
color12               #004b70
color13               #384956
color14               #4d4162
color15               #c1c7ce

# --- Starship Prompt Bubbles ---
color255              #004b70
color254              #96ccf8
color253              #384956
color252              #b7c9d9
color251              #4d4162
color250              #d0c0e8
color249              #93000a
color248              #ffb4ab

color232              #cae6ff
color233              #00344f
color234              #d3e5f6
color235              #22323f
color236              #ebdcff
color237              #362b4a
color238              #ffdad6
color239              #690005
color240              #cae6ff

# Matched with unthemed light/dark
color243              #96ccf8
color244              #ffb4ab
color245              #41474d

# --- UI Elements ---
active_tab_foreground   #00344f
active_tab_background   #96ccf8
inactive_tab_foreground #cae6ff
inactive_tab_background #004b70

active_border_color     #96ccf8
inactive_border_color   #8b9198

# --- Marks ---
mark1_foreground        #001e30
mark1_background        #cae6ff
mark2_foreground        #0c1d29
mark2_background        #d3e5f6
mark3_foreground        #201634
mark3_background        #ebdcff